version: '3'

services:
  db_mysql:
    image: mysql:8.1.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Pa55word@
      MYSQL_DATABASE: db
    volumes:
      - ./db:/var/lib/mysql
